org.gradle.jvmargs=-Xmx3G -XX:+HeapDumpOnOutOfMemoryError -XX:+UseG1GC -XX:MaxGCPauseMillis=200
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

# Only parchment mappings are currently supported
mappings.type = parchment
mappings.version = 2024.11.17

# Environment properties
mod.minecraft=1.21.1
mod.minecraft_range=[1.21.1,1.21.2)
mod.neo_version=21.1.64
mod.neo_range=[21.1.0,)
mod.loader_range=[4,)

## Mod properties

mod.id=kaleidoscope_kitchenware
mod.name=Kaleidoscope Kitchenware
mod.license=BSD-3-Clause
mod.version=0.1.0
mod.group_id=com.kaleidoscope.kitchenware
mod.authors=kaleidoscope_kitchenware contributors
mod.description=A traditional Chinese kitchen furniture and building blocks addon for Kaleidoscope Cookery.
mod.artifact_name=KaleidoscopeKitchenware

# Local addon target version
deps.kaleidoscope_cookery=1.6.0

# Aliyun mirror
maven_url=https://maven.aliyun.com/repository/public
